apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: task-statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "redis-master:6379"
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: password
  - name: actorStateStore
    value: "true"
auth:
  secretStore: kubernetes