apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: audit-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "kafka:9092"
  - name: consumerGroup
    value: "audit-service-consumer-group"
  - name: clientID
    value: "audit-service-client"
  - name: authType
    value: "none"
  - name: maxMessageBytes
    value: "1048576"
  - name: timeoutInSec
    value: "60"
  - name: concurrency
    value: "10"
scopes:
  - audit-service
  - all-services # All services may need to listen to audit events for monitoring