apiVersion: apps/v1
kind: Deployment
metadata:
  name: reminder-service
  labels:
    app: reminder-service
spec:
  replicas: {{ .Values.reminderService.replicaCount }}
  selector:
    matchLabels:
      app: reminder-service
  template:
    metadata:
      labels:
        app: reminder-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "reminder-service"
        dapr.io/app-port: "3001"
        dapr.io/config: "app-config"
        dapr.io/components-path: "/dapr/components"
    spec:
      containers:
      - name: reminder-service
        image: "{{ .Values.reminderService.image.repository }}:{{ .Values.reminderService.image.tag }}"
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_URL
          value: {{ .Values.reminderService.database.url }}
        resources:
{{ toYaml .Values.reminderService.resources | indent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: reminder-service
  labels:
    app: reminder-service
spec:
  selector:
    app: reminder-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP